FROM fluent/fluentd:v1.2.5-onbuild

RUN apk add --update --virtual .build-deps \
       sudo build-base ruby-dev mariadb-dev \
    && sudo gem install \
           fluent-plugin-mysql \
    && sudo gem sources --clear-all \
    && apk del .build-deps \
    && rm -rf /var/cache/apk/* \
              /home/fluent/.gem/ruby/2.4.0/cache/*.gem
